export const customers = [
	{
		id: '1',
		firstName: 'Roshan',
		lastName: 'Adhikari',
		email: 'roshan@test.com',
		phoneNumber: '9817102037',
		profession: 'Engineer',
		nationality: 'Nepali',
		documentId: '123456',
		address: 'Pokhara-8',
	},
	{
		id: '2',
		firstName: 'John',
		lastName: 'Test',
		email: 'john@test.com',
		phoneNumber: '9817102037',
		profession: 'Businessmen',
		nationality: 'Nepali',
		documentId: '123456',
		address: 'Kathmandu',
	},
	{
		id: '3',
		firstName: 'Jack',
		lastName: 'Test',
		email: 'jack@test.com',
		phoneNumber: '9817102037',
		profession: 'Doctor',
		nationality: 'Nepali',
		documentId: '123456',
		address: 'Gorkha',
	},
];
export const reservations = [
	{
		id: '1',
		customerName: 'Roshan Adhikari',
		phoneNumber: '9817102037',
		roomName: 'Super Deluxe Couple AC',
		roomNumber: '106',
		checkIn: '2022-10-22',
		checkOut: '2022-10-26',
		bookingDate: '2022-10-15',
		bookingStatus: 'Confirmed',
		paymentStatus: 'Pending',
	},
	{
		id: '2',
		customerName: 'John Doe',
		phoneNumber: '9817102037',
		roomName: 'Super Deluxe Couple Non AC',
		roomNumber: '106',
		checkIn: '2022-10-22',
		checkOut: '2022-10-26',
		bookingDate: '2022-10-15',
		bookingStatus: 'Confirmed',
		paymentStatus: 'Pending',
	},
	{
		id: '3',
		customerName: 'Code with Dary',
		phoneNumber: '9817102037',
		roomName: 'Deluxe Couple AC',
		roomNumber: '106',
		checkIn: '2022-10-22',
		checkOut: '2022-10-26',
		bookingDate: '2022-10-15',
		bookingStatus: 'Confirmed',
		paymentStatus: 'Pending',
	},
];

export const overviewList = [
	{
		title: 'Today Booking',
		data: '0',
		path: '',
		icon: '',
	},
	{
		title: 'Total Amount',
		data: 'Rs. 31,000',
		path: '',
		icon: '',
	},
	{
		title: 'Total Customer',
		data: '20',
		path: '',
		icon: '',
	},
	{
		title: 'Total Booking',
		data: '150',
		path: '',
		icon: '',
	},
];
